version: "3.9"
services:

    mariadb:
        container_name: "${MARIADB_CONTAINER_NAME}"
        hostname: "${MARIADB_HOSTNAME}"
        image: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
        volumes:
            - ./storage/mariadb:/var/lib/mariadb
        ports:
            - "${MARIADB_PORT}:3306"

    redis:
        image: "${REDIS_IMAGE}"
        container_name: "${REDIS_CONTAINER_NAME}"
        hostname: "${REDIS_HOSTNAME}"
        restart: always
        command: redis-server --requirepass "${REDIS_PASSWORD}"
        environment:
            TZ: "${TZ}"
        volumes:
            - ./storage/redis:/data
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            retries: 3
            timeout: 5s

    minio:
        image: minio/minio
        container_name: "${MINIO_CONTAINER_NAME}"
        hostname: "${MINIO_HOSTNAME}"
        command: minio server /data/minio --console-address ":80"

        environment:
            MINIO_ROOT_USER: ${MINIO_ROOT_USER}
            MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
        volumes:
            - ./storage/minio:/data/minio
        ports:
            - "${MINIO_PORT}:80"

    phpmyadmin:
        image: phpmyadmin
        container_name: "${PHPMYADMIN_CONTAINER_NAME}"
        hostname: "${PHPMYADMIN_HOSTNAME}"
        restart: always
        links:
            - mariadb
        environment:
            UPLOAD_LIMIT: 3000M
            PMA_HOST: mariadb
        ports:
            - "${PHPMYADMIN_PORT}:80"

networks:
    default:
        external: true
        name: production
